### ISSUE TITLE
Queue hangs when copying larger file

### ISSUE THREAD

**Issue by LorenzoRuffati** [millavalio-Unikie/complex-copy#3]
I tested the queue with a larger file and the copy doesn't seem to work with the reader terminating and the writer hanging

![Example of issue](https://user-images.githubusercontent.com/111505340/191902405-eeeb6aec-ac26-476e-8034-445b4f0862ab.png)

[File that fails](https://drive.google.com/file/d/1bFndzj4ae3iOQnRUGmZ6Yhf7PyfgtT0m/view?usp=sharing)

This is a blocking issue for #2

**Comment by LorenzoRuffati** [comment]
This is also failing with pipes #1 
![image](https://user-images.githubusercontent.com/111505340/191903308-9460eefc-3453-414f-847c-9b57bc4f075a.png)

**Comment by LorenzoRuffati** [comment]
@millavalio-Unikie @giangle-unikie

**Comment by giangle-unikie** [comment]
I will change open() to open64() to accept larger file

**Comment by LorenzoRuffati** [comment]
open64 just adds the O_LARGEFILE option to open, that's unlikely to be the problem

I tested this in my and Ferdi's code and it works fine and we just used normal open, O_LARGEFILE should only be required for files larger than 4 GB, this file was ~50 MB so definitely not large enough to create the issue

**Comment by giangle-unikie** [comment]
I got it and fixed it. Now can send and receive well with a larger file.

**Comment by LorenzoRuffati** [comment]
This is solved in the last version of the PR
